### ISSUE TITLE
limit=200 for ticker

### ISSUE THREAD

**Issue by goorooau** [mrsmn/coinmarketcap#22]
get error when limit=200, it's fine if not 200 ie 199, 201, etc

```
from coinmarketcap import Market
coinmarketcap = Market()
markets = coinmarketcap.ticker(limit=200)
```

error:

```
Traceback (most recent call last):
  File "cmc.py", line 50, in <module>
    markets = coinmarketcap.ticker(limit=200)   #limit=200
  File "C:\Python27\lib\site-packages\coinmarketcap\core.py", line 54, in ticker
    response = self.__request('ticker/' + currency, params)
  File "C:\Python27\lib\site-packages\coinmarketcap\core.py", line 28, in __request
    response_object = self.session.get(self.base_url + endpoint, params = params, timeout = self.request_timeout)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests_cache\core.py", line 126, in request
    **kwargs
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests_cache\core.py", line 97, in send
    response, timestamp = self.cache.get_response_and_time(cache_key)
  File "C:\Python27\lib\site-packages\requests_cache\backends\base.py", line 70, in get_response_and_time
    if key not in self.responses:
  File "C:\Python27\lib\_abcoll.py", line 388, in __contains__
    self[key]
  File "C:\Python27\lib\site-packages\requests_cache\backends\storage\dbdict.py", line 163, in __getitem__
    return pickle.loads(bytes(super(DbPickleDict, self).__getitem__(key)))
  File "C:\Python27\lib\copy_reg.py", line 50, in _reconstructor
    obj = base.__new__(cls, state)
TypeError: ('dict.__new__(HTTPHeaderDict): HTTPHeaderDict is not a subtype of dict', <function _reconstructor at 0x02DC9570>, (<class 'urllib3._collections.HTTPHeaderDict'>, <type 'dict'>, {'content-encoding': ('Content-Encoding', 'gzip'), 'transfer-encoding': ('Transfer-Encoding', 'chunked'), 'cf-cache-status': ('CF-Cache-Status', 'EXPIRED'), 'vary': ('Vary', 'Accept-Encoding'), 'server': ('Server', 'cloudflare-nginx'), 'connection': ('Connection', 'keep-alive'), 'date': ('Date', 'Sat, 23 Sep 2017 01:15:20 GMT'), 'access-control-allow-origin': ('Access-Control-Allow-Origin', '*'), 'content-type': ('Content-Type', 'application/json'), 'cf-ray': ('CF-RAY', '3a29a6f978f865f3-SYD')}))

```

**Comment by mrsmn** [comment]
Hello,

I'll look into it and get back to you. Thanks for reporting this.

Cheers.

**Comment by mrsmn** [comment]
This is strange, works fine for me:

```python
Python 2.7.14 (default, Sep 25 2017, 09:53:22)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from coinmarketcap import Market
>>> coinmarketcap = Market()
>>> coinmarketcap.ticker(limit=200)
[{u'market_cap_usd': u'70051264262.0', u'price_usd': u'4222.14', u'last_updated': u'1506584355', u'name': u'Bitcoin', u'24h_volume_usd': u'1903220000.0', u'percent_change_7d': u'8.79', u'symbol': u'BTC', u'rank': u'1', u'percent_change_1h': u'-0.22', u'total_supply': u'16591412.0', u'cached': False, u'price_btc': u'1.0', u'available_supply': u'16591412.0', u'percent_change_24h': u'7.04', u'id': u'bitcoin'}, {u'market_cap_usd': u'28892268974.0', u'price_usd': u'304.595', u'last_updated': u'1506584651', u'name': u'Ethereum', u'24h_volume_usd': u'622251000.0', u'percent_change_7d': u'7.74', u'symbol': u'ETH', u'rank': u'2', u'percent_change_1h': u'-0.28', u'total_supply': u'94854705.0', u'cached': False, u'price_btc': u'0.0719493', u'available_supply': u'94854705.0', u'percent_change_24h': u'5.32', u'id': u'ethereum'}, [...]]
```
Could you please check what version of ```coinmarketcap```, ```requests``` and ```requests-cache``` you're using?

Cheers.

**Comment by mrsmn** [comment]
No reply from user. Don't hesitate to reopen this if this is still an issue.
