### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by iamtpage** [mrsmn/coinmarketcap#23]
I'm using this component in my HomeAssistant installation and when it's configured it throws this exception:
```
2017-12-04 11:42:21 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform coinmarketcap
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/helpers/entity_component.py", line 171, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=self.hass.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/sensor/coinmarketcap.py", line 55, in setup_platform
    CoinMarketCapData(currency, display_currency).update()
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/sensor/coinmarketcap.py", line 133, in update
    convert=self.display_currency)
  File "/usr/local/lib/python3.6/dist-packages/coinmarketcap/core.py", line 54, in ticker
    response = self.__request('ticker/' + currency, params)
  File "/usr/local/lib/python3.6/dist-packages/coinmarketcap/core.py", line 28, in __request
    response_object = self.session.get(self.base_url + endpoint, params = params, timeout = self.request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/coinmarketcap/core.py", line 21, in session
    self._session = requests_cache.core.CachedSession(cache_name='coinmarketcap_cache', backend='sqlite', expire_after=120)
  File "/usr/local/lib/python3.6/dist-packages/requests_cache/core.py", line 68, in __init__
    self.cache = backends.create_backend(backend, cache_name, backend_options)
  File "/usr/local/lib/python3.6/dist-packages/requests_cache/backends/__init__.py", line 50, in create_backend
    return registry[backend_name](cache_name, **options)
  File "/usr/local/lib/python3.6/dist-packages/requests_cache/backends/sqlite.py", line 28, in __init__
    self.responses = DbPickleDict(location + extension, 'responses', fast_save=fast_save)
  File "/usr/local/lib/python3.6/dist-packages/requests_cache/backends/storage/dbdict.py", line 58, in __init__
    with self.connection() as con:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/dist-packages/requests_cache/backends/storage/dbdict.py", line 70, in connection
    con = sqlite.connect(self.filename)
sqlite3.OperationalError: unable to open database file
```

A few other users are experiencing the same issue here: https://github.com/home-assistant/home-assistant/issues/9907

**Comment by mrsmn** [comment]
Hello,

thanks for reporting this, I had no idea the home-assistant project was using this library. Unfortunately there's nothing I can do as the error seems to come from the [home-assistant codebase](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/sensor/coinmarketcap.py).

I'll keep an eye out and if nobody fixes this I'll try and come up with a PR downstream.

Cheers.

**Comment by franlab** [comment]
Hi, I am having the same issue without using home-assistant.

I just followed this example: http://blockxchain.org/2017/05/29/importing-altcoin-data-with-python-and-the-coinmarketcap-api/

Thanks!

**Comment by mrsmn** [comment]
Hello @franlab,

can you share the exact code you're using (either on Pastebin or in a gist) so I can have a closer look. I've not been able to reproduce this error so far.

Cheers.

**Comment by franlab** [comment]
Hello @mrsmn thanks for the response. 

This is my code:
https://pastebin.com/EMg73zu8

and here is the code I am using to run the api within a llinux daemon: https://pastebin.com/9xA6hFbr which I borrowed from: http://web.archive.org/web/20131017130434/http://www.jejik.com/articles/2007/02/a_simple_unix_linux_daemon_in_python/

**Comment by mrsmn** [comment]
Hey @franlab,

thanks for sharing, I'll look into the issue over the weekend. I have an idea where the error might come from, I'll need to do some testing.

Cheers.

**Comment by mrsmn** [comment]
Hello again,

so I was able to get a look at the code @franlab posted: the codebase looks sane but keeps on complaining that it can't open the DB file. Adding a manual path (for example ```/home/<user>/coinmarketcap```) to the class instanciation doesn't seem to cut it.

If I had to take a guess I'd say it's the voodoo-black-magic forking of the daemon class that's at fault but I'll have to ```pdb```it to be sure.

**Comment by themightydeity** [comment]
@mrsmn I see that you have been using request_cache but the path for sqlite  db cache is `/` (not correct) when Python is running under wsgi daemon processes, it would be nice to set that location from this library as well. Example on how it is being done in Django: [https://github.com/allianceauth/allianceauth/issues/224#issuecomment-177646284](url). This would solve permission issues.

**Comment by mrsmn** [comment]
Thanks @themightydeity, I'll look into it over the weekend. 👍

**Comment by Klathmon** [comment]
It might not be a full solution, but changing the `backend` to `memory` on [this line](https://github.com/mrsmn/coinmarketcap/blob/816c05f2ee09c10f48af3b31686da2ff4da3416c/coinmarketcap/core.py#L21) solves the problem for me.

Leaving it off will have it use `sqlite` if it's available, and fallback to `memory` if it's not ([according to the docs](http://requests-cache.readthedocs.io/en/latest/api.html)) so that might be an option as well.

**Comment by jathpala** [comment]
Might be worth someone trying this again with the latest commit. I wonder if the issue was that the current working directory in this situation was one that the user did not have write permission for. The cache file is now stored in a system temp directory which should be writable.

**Comment by mrsmn** [comment]
Should be fixed in v.4.2.0 or in https://github.com/mrsmn/coinmarketcap/commit/c608a3d7805a4d408794dbf0bf5e0f69e715dae6.
