### ISSUE TITLE
New install, and get "database is locked"

### ISSUE THREAD

**Issue by CptanPanic** [mrsmn/coinmarketcap#29]
When I try for the first time using call 'coinmarketcap.ticker('VTC', limit=3, convert='USD')' I get the following error using python3.  Note the cache file is actually created, but it is 0 size.

```
Traceback (most recent call last):
  File "vtc_wallet.py", line 30, in <module>
    price = get_vtc_price()
  File "vtc_wallet.py", line 21, in get_vtc_price
    coinmarketcap.ticker('VTC', limit=3, convert='USD')
  File "/usr/local/lib/python3.5/dist-packages/coinmarketcap/core.py", line 54, in ticker
    response = self.__request('ticker/' + currency, params)
  File "/usr/local/lib/python3.5/dist-packages/coinmarketcap/core.py", line 28, in __request
    response_object = self.session.get(self.base_url + endpoint, params = params, timeout = self.request_timeout)
  File "/usr/local/lib/python3.5/dist-packages/coinmarketcap/core.py", line 21, in session
    self._session = requests_cache.core.CachedSession(cache_name='coinmarketcap_cache', backend='sqlite', expire_after=120)
  File "/usr/local/lib/python3.5/dist-packages/requests_cache/core.py", line 68, in __init__
    self.cache = backends.create_backend(backend, cache_name, backend_options)
  File "/usr/local/lib/python3.5/dist-packages/requests_cache/backends/__init__.py", line 50, in create_backend
    return registry[backend_name](cache_name, **options)
  File "/usr/local/lib/python3.5/dist-packages/requests_cache/backends/sqlite.py", line 28, in __init__
    self.responses = DbPickleDict(location + extension, 'responses', fast_save=fast_save)
  File "/usr/local/lib/python3.5/dist-packages/requests_cache/backends/storage/dbdict.py", line 59, in __init__
    con.execute("create table if not exists `%s` (key PRIMARY KEY, value)" % self.table_name)
sqlite3.OperationalError: database is locked
```

**Comment by mrsmn** [comment]
Hey @CptanPanic,

could you please try using the coin ID instead of the symbol.

```python
coinmarketcap.ticker('vertcoin', limit=3, convert='USD')
```

**Comment by CptanPanic** [comment]
Turns out that it was due to running it in a mounted cifs directory.  And I needed to use 'vertcoin' instead of 'vtc'
